<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1491289913167" stop="1491289918204">
	<name>Protractor Demo App</name>
	<title>Protractor Demo App</title>
	<test-cases>
		<test-case start="1491289913167" stop="1491289918204" status="failed">
			<name>should add one and two</name>
			<title>should add one and two</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
			</attachments>
			<failure>
				<message>Expected &apos;3&apos; to equal &apos;5&apos;.</message>
				<stack-trace>Error: Failed expectation
    at Object.&lt;anonymous&gt; (F:\Protractor\New\binding.js:11:9)
    at C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:110:25
    at new ManagedPromise (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
    at ControlFlow.promise (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
    at schedulerExecute (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2860:25)
    at C:\Users\sarkar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>